# Generated by Django 3.2.22 on 2023-10-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_title', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('dish_image', models.ImageField(upload_to='')),
                ('dish_time', models.TimeField()),
                ('dish_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
