# Generated by Django 3.2.22 on 2023-10-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='ingredients',
            new_name='dish_ingredients',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='dish_time',
        ),
    ]
