# Generated by Django 3.2.22 on 2023-10-26 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231026_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 12, 5, 5, 732319), verbose_name='date published'),
        ),
    ]
