# Generated by Django 4.2.16 on 2024-11-12 19:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231026_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_cooking_process',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_image',
            field=models.ImageField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_published',
            field=models.DateField(default=datetime.datetime(2024, 11, 12, 19, 58, 6, 738783), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_title',
            field=models.CharField(max_length=35),
        ),
    ]
